### ISSUE TITLE
Add support for sending and reading Notifications

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-client#114]
Add helper functions to:
* send Solid Notifications
* read and parse notifications from an Inbox

For reference, see:
* [Solid Notifications proposal](https://github.com/solid/solid/blob/master/proposals/notifications.md)
* [Linked Data Notifications spec](https://rawgit.com/csarven/ldn/master/index.html)

**Comment by dmitrizagidulin** [comment]
API:

```js
var options = {
    title: 'Notification title',
    body: 'Notification contents',
    from: ALICE_WEBID,
    to: BOB_WEBID
}
var notification = new SolidNotification(options)
solid.sendNotification(notification)
  .then(function (result) {
    // Notification sent.
  })
```

**Comment by csarven** [comment]
Is https://github.com/solid/solid-client/pull/115 up to date with:

Editor's Draft: https://linkedresearch.org/ldn/ (same as the rawgit) or
Latest published version: https://www.w3.org/TR/ldn/

**Comment by dmitrizagidulin** [comment]
Not quite, it'll need some work. Looking into it this morning.

**Comment by dmitrizagidulin** [comment]
Closing, out of scope for this repo. Notifications work moved to https://github.com/solid/solid-notifications
