### ISSUE TITLE
Deprecate solid.web.list in README

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-client#118]
As per [conversation](https://gitter.im/solid/chat?at=57a87c87978997001ea01a26)

> right, solid.web.list has been deprecated for just solid.web.get (looks like I forgot to update the example in the readme)

Regarding listing a solid container

https://github.com/solid/solid-client#listing-a-solid-container

**Comment by dmitrizagidulin** [comment]
Fixed in latest commit. Thanks!

**Comment by melvincarvalho** [comment]
seeAlso https://github.com/solid/solid-client/issues/85
