### ISSUE TITLE
Export solid-permission's Authorization and PermissionSet classes

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-client#125]
`solid-client` currently only exposes `getPermissions()` and `clearPermissions()` functions.
To create new ACL resources, a developer would need to use the `PermissionSet` class.
So, the top level client needs to expose/export the key classes from `solid-permissions`.

**Comment by elf-pavlik** [comment]
Currently also `solid.acl` ends up with undefined value, so this snipped will not work - https://github.com/solid/solid-client#editing-permissions

**Comment by elf-pavlik** [comment]
I recommend to make the whole *solid-permissions* module available via `solid.acl` and simply change *solid-permissions* so that it exports all the constants so one can do both
* `solid.acl.ALL`
* `new solid.acl.PermissionSet`

**Comment by dmitrizagidulin** [comment]
Fixed in latest release, v0.22.5. Closing.
