### ISSUE TITLE
solid:ListedDocument and solid:UnlistedDocument confusing

### ISSUE THREAD

**Issue by dan-f** [solid/solid-client#146]
https://github.com/solid/solid-client/blob/96f214da16da8139c6cfe8ea79b57c888657e949/src/registry.js#L30

This query (and the one above) are not specific enough (subject should be a NamedNode of the graph's URI).

Moreover, the usefulness of the listed/unlisted concept is not clear to me, especially given how our access control system works.

cc @timbl

**Comment by dmitrizagidulin** [comment]
The query issue is fixed in PR #150, closing.
