### ISSUE TITLE
The PATCH function returns invalid Turtle

### ISSUE THREAD

**Issue by deiu** [solid/solid-client#149]
The function that prepares the PATCH request currently returns invalid turtle (i.e. no trailing dot) if it encounters a single statement.

Fix: it shouldn't remove the trailing dot if the length of `toDel` and `toAdd` is equal to 1.

https://github.com/solid/solid-client/blob/96f214da16da8139c6cfe8ea79b57c888657e949/src/util/web-util.js#L134-L150

**Comment by dmitrizagidulin** [comment]
@deiu thanks! I'll fix it shortly.
