### ISSUE TITLE
Update config.proxyUrl once databox2.com goes live

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-client#63]
Once databox2.com is up and running a proxy endpoint, update the default `proxyUrl` in the config file to point to `https://databox2.com/proxy?uri={uri}` instead of the current databox address.

**Comment by deiu** [comment]
Is there a reason why we want to do that?

**Comment by dmitrizagidulin** [comment]
Yes, for two reasons.

1. Gold's proxy currently has a bug - see https://github.com/linkeddata/gold/issues/67 that is messing with some profile loading use cases
2. Once [ldnode/#258-Add ability for Proxy to follow redirects](https://github.com/linkeddata/ldnode/issues/258) gets implemented, ldnode's proxy will be preferable to gold's feature-wise.

**Comment by deiu** [comment]
Gold added a fix in 6c754b10cdc0d9fc096442428cf101687983cdd5

**Comment by timbl** [comment]
Also removing the cross-dependency increases the robustness -- you don't have to have both running to do anything

**Comment by dmitrizagidulin** [comment]
Closing, no longer relevant.
